server:
  port: 9001

feign:
  client:
    config:
      default:
        connectTimeout: 45000
        readTimeout: 45000

spring:
  application:
    name: auth-service

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
  expiration: 300